server:
  port: 8600

spring:
 application:
   name: e-storage
 data:
   cassandra:
     contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
     keyspace-name: ocds
     port: 9042
     username: caclient
     password: brT4Kn27RQs
 servlet:
   multipart:
     enabled: true
     max-file-size: 60Mb

upload:
 file:
   max-weight: 60
   path: https://storage.eprocurement.systems/get/
   folder: /home/user/storage
   extensions: jpg,png,gif,tif,rar,zip,7s,doc,docx,xls,xlsx,pdf,rtf,txt