spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storagedb?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: storage
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50Mb

upload.file.path: /home/user/storage/


