spring:
  datasource:
    url: jdbc:mysql://localhost/storagedb?useSSL=false
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: storage
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

upload.file.path: /home/user/storage/