server:
  port: 8080
  tomcat:
     max-connections: 10 # Maximum number of connections that the server will accept and process at any given time.
     max-threads: 10

spring:
  application:
    name: e-storage
  servlet:
    multipart:
      enabled: true
      max-file-size: 50Mb
      max-request-size: 50Mb

cassandra:
  contact-points: 127.0.0.1
  keyspace-name: ocds
  port: 9042
  username: cassandra
  password: cassandra

upload:
  file:
    max-weight: 52428800
    path: http://bpe.eprocurement.systems/api/v1/storage/get/
    folder: /home/user/storage
    extensions: jpg,png,gif,tif,rar,zip,7s,doc,docx,xls,xlsx,pdf,rtf,txt

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full